dbproject/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('', include('index.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

index/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'index'
urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('einsatz/', views.EinsatzView.as_view(), name='einsatz'),
    path('einsatz/add', views.EinsatzCreate.as_view(), name='einsatz-create'),
    path('einsatz/upd/<int:pk>/', views.EinsatzUpdate.as_view(), name='einsatz-update'),
    path('einsatz/del/<int:pk>/', views.EinsatzDelete.as_view(), name='einsatz-delete'),
    path('dienst/', views.DienstView.as_view(), name='dienst'),
    path('dienst/add', views.DienstCreate.as_view(), name='dienst-create'),
    path('dienst/upd/<int:pk>/', views.DienstUpdate.as_view(), name='dienst-update'),
    path('dienst/del/<int:pk>/', views.DienstDelete.as_view(), name='dienst-delete'),
    path('rettungsmittel/', views.RettungsmittelView.as_view(), name='rettungsmittel'),
    path('rettungsmittel/add', views.RettungsmittelCreate.as_view(), name='rettungsmittel-create'),
    path('rettungsmittel/upd/<int:pk>/', views.RettungsmittelUpdate.as_view(), name='rettungsmittel-update'),
    path('rettungsmittel/del/<int:pk>/', views.RettungsmittelDelete.as_view(), name='rettungsmittel-delete'),
    path('patient/', views.PatientView.as_view(), name='patient'),
    path('patient/add', views.PatientCreate.as_view(), name='patient-create'),
    path('patient/upd/<int:pk>/', views.PatientUpdate.as_view(), name='patient-update'),
    path('patient/del/<int:pk>/', views.PatientDelete.as_view(), name='patient-delete'),
    path('vorfall/', views.VorfallView.as_view(), name='vorfall'),
    path('vorfall/add', views.VorfallCreate.as_view(), name='vorfall-create'),
    path('vorfall/det/<int:pk>/', views.VorfallDetailView.as_view(), name='vorfall-detail'),
    path('vorfall/upd/<int:pk>/', views.VorfallUpdate.as_view(), name='vorfall-update'),
    path('vorfall/del/<int:pk>/', views.VorfallDelete.as_view(), name='vorfall-delete'),
    path('personal/', views.PersonalView.as_view(), name='personal'),
    path('personal/add', views.PersonalCreate.as_view(), name='personal-create'),
    path('personal/upd/<int:pk>/', views.PersonalUpdate.as_view(), name='personal-update'),
    path('personal/del/<int:pk>/', views.PersonalDelete.as_view(), name='personal-delete'),
    path('ansprechpartner/', views.AnsprechpartnerView.as_view(), name='ansprechpartner'),
    path('ansprechpartner/add', views.AnsprechpartnerCreate.as_view(), name='ansprechpartner-create'),
    path('ansprechpartner/upd/<int:pk>/', views.AnsprechpartnerUpdate.as_view(), name='ansprechpartner-update'),
    path('ansprechpartner/del/<int:pk>/', views.AnsprechpartnerDelete.as_view(), name='ansprechpartner-delete'),
]

index/models.py
from django.db import models
from datetime import datetime
from datetime import date
from django.core import validators
from django.urls import reverse


class Personal(models.Model):
    Vorname = models.CharField(max_length=50)
    Name = models.CharField(max_length=50)
    Führungsqualifikation = models.CharField(max_length=50)
    Bereitschaft = models.CharField(max_length=20)
    Qualifikation = models.CharField(max_length=20)

#   mehr als das muss in der models.py nicht geändert werden
    def get_absolute_url(self):
        if self == self:
            return ('/personal/')
#   mehr is es echt nicht xD
    def __str__(self):
        return self.Vorname+' '+self.Name

class Einsatz(models.Model):
    Personal_ID = models.ForeignKey(Personal, on_delete=models.CASCADE)
    Einsatzdatum = models.DateField('Einsatzdatum', default=date.today)
    Einsatzinfo = models.CharField('Einsatzinfo', max_length=254, default='Einsatzinfo')    
    
    def get_absolute_url(self):
        if self == self:
            return ('/einsatz/')

    def __str__(self):
        return self.Einsatzinfo


class Dienst(models.Model):
#   Dienstdatum = models.DateField('Dienstdatum', default=date.today)
    Personal_ID = models.ForeignKey(Personal, default="1", on_delete=models.DO_NOTHING)
    Einsatz_ID = models.ForeignKey(Einsatz, default="1", on_delete=models.DO_NOTHING)
    Einsatzbeginnzeit = models.TimeField('Einsatzbeginn')
    Funkrufname = models.CharField(max_length=20)
    Einsatzendezeit = models.TimeField('Einsatzende',  blank=True, null=True, default= "00:00:00")
    
    def get_absolute_url(self):
        if self == self:
            return ('/dienst/')

    def __str__(self):
        return str(self.Personal_ID)


class Ansprechpartner(models.Model):
    sex = (('w', 'W'), ('m', 'M'))
    Einsatz_ID = models.ForeignKey(Einsatz, default='1', on_delete=models.CASCADE)
#    Datum = models.DateField('Datum', default=date.today)
    Telefonnummer = models.CharField(max_length=20)
    Geschlecht = models.CharField(max_length=1, choices=sex, default='W')
    Vorname = models.CharField(max_length=20)
    Name = models.CharField(max_length=20)
    Infotext = models.CharField(max_length=100)

    def get_absolute_url(self):
        if self == self:
            return ('/ansprechpartner/')

    def __str__(self):
        return self.Vorname+' '+self.Name


class Rettungsmittel(models.Model):
    Bezeichnung = models.CharField(max_length=30)
   
    def get_absolute_url(self):
        if self == self:
            return ('/rettungsmittel/')

    def __str__(self):
        return self.Bezeichnung



class Patient(models.Model):
    sex = (('w', 'W'), ('m', 'M'))

    Vorname = models.CharField(max_length=20, default='Patientin')
    Name = models.CharField(max_length=20, default='Musterfrau')
    Alter = models.IntegerField(validators=(validators.MinValueValidator(0), validators.MaxValueValidator(110)))
    Geschlecht = models.CharField(max_length=1, choices=sex, default='W')

    def __str__(self):
        return self.Vorname+' '+self.Name
    
    def get_absolute_url(self):
        if self == self:
            return ('/patient/')



class Vorfall(models.Model):
    triag = (('geringes Risiko', 'GERINGES RISIKO'),
        ('mittleres Risiko', 'MITTLERES RISIKO'),
        ('hohes Risiko', 'HOHES RISIKO'),
    )
    Einsatz = models.ForeignKey(Einsatz, default='1', on_delete=models.CASCADE)
#   Einsatzdatum = models.DateField('Einsatzdatum', default=date.today)
    Einsatzort = models.CharField(max_length=50, default='Heidenheim', editable=True)
    Einsatzbeginn = models.TimeField('Einsatzbeginn', default=datetime.now)
    Einsatzende = models.TimeField('Einsatzende', blank=True, null=True, default= "00:00:00")
    Triagekategorie = models.CharField('Triagekategorie', max_length=21, default='LEICHTE VERLETZUNGEN', choices=triag)
    Dienst = models.ManyToManyField(Dienst)
    Retter = models.ManyToManyField(Rettungsmittel)
    Patient = models.ManyToManyField(Patient, blank=True)

    def __str__(self):
        return self.Einsatzort

    def get_absolute_url(self):
        if self == self:
            return ('/vorfall/')

index/templates/index/dienst_confirm_delete.html
{% extends "index/layout.html" %}
{% load static %}
{% block main %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />


<h2>Dienst löschen</h2>
{% if perms.index.delete_dienst %}
<form action="" method="post">{% csrf_token %}
    <p>Sind Sie sicher, dass sie diesen Dienst "{{ object }}" löschen wollen?</p>
    <input type="submit" class="btn btn-success" role="button" value="Ja" />
    <a href="/dienst/" class="btn btn-danger" role="button">abbrechen</a>
</form>
{% else %}
 <h2>Sie verfügen nicht über ausreichende Berechtigungen</h2>
{% endif %}
{% endblock %}

index/templates/index/einsatz_add.html
{% extends "index/layout.html" %}
{% load static %}
{% block main %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />


<h2>Einsatz</h2>
{% if perms.index.add_einsatz %}
<form class="site-form" action=" " method ="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success">Speichern</button>
      <a href="/einsatz/" class="btn btn-danger" role="button">abbrechen</a>
</form>
{% else %}
 <h2>Sie verfügen nicht über ausreichende Berechtigungen</h2>
{% endif %}
{% endblock %}

index/templates/index/patient.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/docs/examples/dashboard/dashboard.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'bootstrap/favicon.png' %}" />
    <title>Patient anlegen</title>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="{% static 'bootstrap/favicon.png' %}" width="30" height="30"></a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/ansprechpartner">Ansprechpartner</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/personal">Personal</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/rettungsmittel">Rettungsmittel</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/admin">Admin</a>
          </li>

          {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">logout</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>


    <div class="container-fluid">
      <div class="row">

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-1 pt-3">
          <br>
          <h1>Patient anlegen</h1>
            <section class="row text-center placeholders">
            <div class="col-6 col-sm-3 placeholder">
                <a href="/einsatz"><div id="kreis" style="background-color: #0275D8"><H2>Einsatz</H2></div></a>
            </div>

            <div class="col-6 col-sm-3 placeholder">
                <a href="/dienst"><div id="kreis" style="background-color: #00DC83"><H2>Dienst</H2></div></a>
            </div>

            <div class="col-6 col-sm-3 placeholder">
                <a href="/vorfall"><div id="kreis" style="background-color: #D9534F"><H2>Vorfall</H2></div></a>
            </div>

            <div class="col-6 col-sm-3 placeholder">
                <a href="/patient"><div id="kreis" style="background-color: #00DC83"><H2>Patient</H2></div></a>
            </div>
          </section>

        </main>
      </div>
    </div>

     <div class="container col-sm-9 offset-sm-3 col-md-10 offset-md-1 pt-3">
      <h2>Patient</h2>
         <div class="row">

          <div class="col-lg-2 portfolio-item pb-2">
            {% if  perms.index.add_patient %}
            <a href="/patient/add" class="btn btn-success btn-block" role="button">Hinzufügen</a>
            {% else %}
            <button class="btn btn-secondary">Hinzufügen</button>
            {% endif %}
          </div>


          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Vorname</th>
                  <th>Name</th>
                  <th>Alter</th>
                  <th>Geschlecht</th>
                  <th>Ändern</th>
                  <th>Löschen</th>
                </tr>
              </thead>
              <tbody>


{% if liste %}
    {% for x in liste %}
        <tr>
            <td>{{ x.Vorname }}</td>
            <td>{{ x.Name }}</td>
            <td>{{ x.Alter }}</td>
            <td>{{ x.Geschlecht }}</td>
            {% if  perms.index.change_patient %}
            <td><a href="/patient/upd/{{ x.id }}" class="btn btn-warning" role="button">Ändern</a></td>
            {% else %}
            <td><button class="btn btn-secondary">Ändern</button> </td>
            {% endif %}
            {% if perms.index.delete_patient %}
            <td><a href="/patient/del/{{ x.id }}" class="btn btn-danger" role="button">Löschen</a></td>
            {% else %}
            <td><button class="btn btn-secondary">Löschen</button> </td>
            {% endif %}
        </tr>
    {% endfor %}

{% else %}
        <tr>
            <td>Hat leider nicht funktioniert</td>
        </tr>
{% endif %}
              </tbody>
            </table>
          </div>

          </main>
      </div>
    </div>
    <!-- ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'bootstrap/docs/assets/js/vendor/jquery.slim.min.js' %}"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
  </body>
</html>

index/templates/index/patient_add.html
{% extends "index/layout.html" %}
{% load static %}
{% block main %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />


<h2>Patient</h2>
{% if perms.index.add_patient %}
<form class="site-form" action=" " method ="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success">Speichern</button>
      <a href="/patient/" class="btn btn-danger" role="button">abbrechen</a>
</form>
{% else %}
 <h2>Sie verfügen nicht über ausreichende Berechtigungen</h2>
{% endif %}
{% endblock %}

index/templates/index/patient_update.html
{% extends "index/layout.html" %}
{% load static %}
{% block main %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />



      <h2>Patient</h2>
{% if perms.index.change_patient %}
             <form action="" method="post">{% csrf_token %}
                 {{ form.as_p }}

                 <button type="submit" class="btn btn-success">Speichern</button>
                 <a href="/patient/" class="btn btn-danger" role="button">abbrechen</a>
             </form>
{% else %}
 <h2>Sie verfügen nicht über ausreichende Berechtigungen</h2>
{% endif %}
{% endblock %}

index/templates/index/personal.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/docs/examples/dashboard/dashboard.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'bootstrap/favicon.png' %}" />
    <title>Personal anlegen</title>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
      <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/"><img src="{% static 'bootstrap/favicon.png' %}" width="30" height="30"></a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/ansprechpartner">Ansprechpartner</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/personal">Personal</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/rettungsmittel">Rettungsmittel</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/admin">Admin</a>
          </li>

          {% if user.is_authenticated %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">logout</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>


    <div class="container-fluid">
      <div class="row">

        <main class="col-sm-9 offset-sm-3 col-md-10 offset-md-1 pt-3">
          <br>
          <h1>Personal anlegen</h1>
            <section class="row text-center placeholders">

            <div class="col-6 col-sm-3 placeholder">
                <a href="/einsatz"><div id="kreis" style="background-color: #0275D8"><H2>Einsatz</H2></div></a>
            </div>

            <div class="col-6 col-sm-3 placeholder">
                <a href="/dienst"><div id="kreis" style="background-color: #00DC83"><H2>Dienst</H2></div></a>
            </div>

            <div class="col-6 col-sm-3 placeholder">
                <a href="/vorfall"><div id="kreis" style="background-color: #D9534F"><H2>Vorfall</H2></div></a>
            </div>

            <div class="col-6 col-sm-3 placeholder">
                <a href="/patient"><div id="kreis" style="background-color: #00DC83"><H2>Patient</H2></div></a>
            </div>

          </section>

        </main>
      </div>
    </div>

     <div class="container col-sm-9 offset-sm-3 col-md-10 offset-md-1 pt-3">
      <h2>Personal</h2>
         <div class="row">

          <div class="col-lg-2 portfolio-item pb-2">
              <!-- neuer Button zum addennnnnnnnnnnnnnnnnnnnnn -->
            {% if  perms.index.add_personal %}
            <a href="/personal/add" class="btn btn-success btn-block" role="button">Hinzufügen</a>
            {% else %}
            <button class="btn btn-secondary">Hinzufügen</button>
            {% endif %}
          </div>

            <br>

          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Vorname</th>
                  <th>Name</th>
                  <th>Führungsqualifikation</th>
                  <th>Bereitschaft</th>
                  <th>Qualifikation</th>
                    <!-- Spaltenüberschriften der neuen Spalten -->
                  <th>Ändern</th>
                  <th>Löschen</th>
                </tr>
              </thead>
              <tbody>

{% if liste %}
    {% for x in liste %}

        <tr>
            <td>{{ x.Vorname }}</td>
            <td>{{ x.Name }}</td>
            <td>{{ x.Führungsqualifikation }}</td>
            <td>{{ x.Bereitschaft }}</td>
            <td>{{ x.Qualifikation }}</td>
            <!-- neue Spalten in der Tabelle mit Buttons zum ändern/löschen -->
            {% if  perms.index.change_personal %}
            <td><a href="/personal/upd/{{ x.id }}" class="btn btn-warning" role="button">Ändern</a></td>
            <!-- <td><a href="/admin/index/personal/1/change/?_to_field=id&_popup={{ x.id }}" class="btn btn-warning" role="button">Ändern</a></td> -->
            {% else %}
            <td><button class="btn btn-secondary">Ändern</button> </td>
            {% endif %}
            {% if perms.index.delete_personal %}
            <td><a href="/personal/del/{{ x.id }}" class="btn btn-danger" role="button">Löschen</a></td>
            {% else %}
            <td><button class="btn btn-secondary">Löschen</button> </td>
            {% endif %}
        </tr>
    {% endfor %}

{% else %}
        <tr>
            <td>Hat leider nicht funktioniert</td>
            <td>Hat leider nicht funktioniert</td>
            <td>Hat leider nicht funktioniert</td>
            <td>Hat leider nicht funktioniert</td>
            <td>Hat leider nicht funktioniert</td>
            <td>Hat leider nicht funktioniert</td>
            <td>Hat leider nicht funktioniert</td>
        </tr>
{% endif %}
              </tbody>
            </table>
          </div>

          </main>
      </div>
    </div>
    <!-- ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'bootstrap/docs/assets/js/vendor/jquery.slim.min.js' %}"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
  </body>
</html>

index/templates/index/personal_add.html
{% extends "index/layout.html" %}
{% load static %}
{% block main %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />


<h2>Personal</h2>
{% if perms.index.add_personal %}
<form class="site-form" action=" " method ="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success">Speichern</button>
      <a href="/personal/" class="btn btn-danger" role="button">abbrechen</a>
</form>
{% else %}
 <h2>Sie verfügen nicht über ausreichende Berechtigungen</h2>
{% endif %}
{% endblock %}

index/templates/index/personal_confirm_delete.html
{% extends "index/layout.html" %}
{% load static %}
{% block main %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />


<h2>Personal löschen</h2>
{% if perms.index.delete_personal %}
<form action="" method="post">{% csrf_token %}
    <p>Sind Sie sicher, dass sie die Personalie "{{ object }}" löschen wollen?</p>
    <input type="submit" class="btn btn-success" role="button" value="Ja" />
    <a href="/personal/" class="btn btn-danger" role="button">abbrechen</a>
</form>
{% else %}
 <h2>Sie verfügen nicht über ausreichende Berechtigungen</h2>
{% endif %}
{% endblock %}

index/templates/index/personal_update.html
{% extends "index/layout.html" %}
{% load static %}
{% block main %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />

      <h2>Personal</h2>
{% if perms.index.change_personal %}
             <form action="" method="post">{% csrf_token %}
                 {{ form.as_p }}

                 <button type="submit" class="btn btn-success">Speichern</button>
                 <a href="/personal/" class="btn btn-danger" role="button">abbrechen</a>
             </form>
{% else %}
 <h2>Sie verfügen nicht über ausreichende Berechtigungen</h2>
{% endif %}
{% endblock %}

index/templates/index/rettungsmittel_add.html
{% extends "index/layout.html" %}
{% load static %}
{% block main %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />


<h2>Rettungsmittel</h2>
{% if perms.index.add_rettungsmittel %}
<form class="site-form" action=" " method ="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success">Speichern</button>
      <a href="/rettungsmittel/" class="btn btn-danger" role="button">abbrechen</a>
</form>
{% else %}
 <h2>Sie verfügen nicht über ausreichende Berechtigungen</h2>
{% endif %}
{% endblock %}

index/templates/index/rettungsmittel_confirm_delete.html
{% extends "index/layout.html" %}
{% load static %}
{% block main %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />


<h2>Rettungsmittel löschen</h2>
{% if perms.index.delete_rettungsmittel %}
<form action="" method="post">{% csrf_token %}
    <p>Sind Sie sicher, dass sie dieses Rettungsmittel "{{ object }}" löschen wollen?</p>
    <input type="submit" class="btn btn-success" role="button" value="Ja" />
    <a href="/rettungsmittel/" class="btn btn-danger" role="button">abbrechen</a>
</form>
{% else %}
 <h2>Sie verfügen nicht über ausreichende Berechtigungen</h2>
{% endif %}
{% endblock %}

index/templates/index/rettungsmittel_update.html
{% extends "index/layout.html" %}
{% load static %}
{% block main %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" />



      <h2>Rettungsmittel</h2>
{% if perms.index.change_rettungsmittel %}
             <form action="" method="post">{% csrf_token %}
                 {{ form.as_p }}

                 <button type="submit" class="btn btn-success">Speichern</button>
                 <a href="/rettungsmittel/" class="btn btn-danger" role="button">abbrechen</a>
             </form>
{% else %}
 <h2>Sie verfügen nicht über ausreichende Berechtigungen</h2>
{% endif %}
{% endblock %}